name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  svelteCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run Svelte Check
        run: pnpm run check
    env:
      SUPABASE_SERVICE_KEY: temp-value-for-SUPABASE_SERVICE_KEY
      PUB_VITE_SUPABASE_URL: temp-value-for-PUB_VITE_SUPABASE_URL
      PUB_ARGYLE_LINK_URL: temp-value-for-PUB_ARGYLE_LINK_URL
      SUPABASE_DEFAULT_PASSWORD: temp-value-for-SUPABASE_DEFAULT_PASSWORD
      PUB_VITE_SUPABASE_ANON_KEY: temp-value-for-PUB_VITE_SUPABASE_ANON_KEY
      PUB_VITE_TWILIO_SID: AC123456789
      VITE_TWILIO_TOKEN: temp-value-for-VITE_TWILIO_TOKEN
      VITE_TWILIO_NUMBER: temp-value-for-VITE_TWILIO_NUMBER
  formatAndLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Check formatting
        run: pnpm format
      - name: Check linting
        run: pnpm lint
  types:
    runs-on: ubuntu-latest
    environment: Testing

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Start Supabase local development setup
        run: npx supabase start
      - name: Generate types and format them
        run: |
          npx supabase gen types typescript --local > src/lib/schema.ts
          pnpm run format:fix
      - name: Verify types are up to date
        run: |
          if ! git diff --ignore-space-at-eol --exit-code --quiet src/lib/schema.ts; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
    env:
      VITE_TWILIO_TOKEN: 'temp-value-for-ci'
  playwright:
    runs-on: ubuntu-22.04
    environment: Testing
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - uses: supabase/setup-cli@v1
        with:
          version: 2.19.5
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run the e2e tests
        run: |
          supabase start
          supabase status --output env >> tempenv.txt
          sed -e '/^API_URL/s//PUB_VITE_SUPABASE_URL/' -e '/^SERVICE_ROLE_KEY/s//SUPABASE_SERVICE_KEY/' -e '/^ANON_KEY/s//PUB_VITE_SUPABASE_ANON_KEY/' tempenv.txt >> .env
          supabase db reset
          npm run test:e2e
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
    env:
      VITE_ARGYLE_API_KEY: ${{ secrets.VITE_ARGYLE_API_KEY }}
      VITE_ARGYLE_API_SECRET: ${{ secrets.VITE_ARGYLE_API_SECRET }}
      PUB_ARGYLE_LINK_URL: https://api-sandbox.argyle.com
      PUB_VITE_TWILIO_SID: AC123456789
      SUPABASE_DEFAULT_PASSWORD: temp-value-for-SUPABASE_DEFAULT_PASSWORD
      VITE_TWILIO_NUMBER: temp-value-for-VITE_TWILIO_NUMBER
      VITE_TWILIO_TOKEN: temp-value-for-VITE_TWILIO_TOKEN
  vitest:
    runs-on: ubuntu-22.04
    environment: Testing
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - uses: supabase/setup-cli@v1
        with:
          version: 2.19.5
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: |
          supabase start
          supabase status --output env >> tempenv.txt
          sed -e '/^API_URL/s//PUB_VITE_SUPABASE_URL/' -e '/^SERVICE_ROLE_KEY/s//SUPABASE_SERVICE_KEY/' -e '/^ANON_KEY/s//PUB_VITE_SUPABASE_ANON_KEY/' tempenv.txt >> .env
          supabase db reset
          npm run test
    env:
      PUB_VITE_TWILIO_SID: AC123456789
      VITE_TWILIO_TOKEN: abcdefghijklmnopqrstuvwxyz
