import { jsPDF } from 'jspdf';
import type { RequestEvent } from './$types';
import { formatPhoneNumber } from '@src/lib/utils';

export const POST = async (event: RequestEvent) => {
  const { safeGetSession } = event.locals;
  const { user } = await safeGetSession();

  if (!user) {
    return new Response('No user found', { status: 404 });
  }

  const {
    driverFullName,
    driverEmail,
    driverPhone,
    referencePeriodString,
    deactivationPeriodString,
    totalNumberOfTrips,
    averageDailyPayString,
    grossEstimatedLostPay,
    grossEstimatedLostPayWithInterest,
    annualInterestRateAsString,
    selectedEmployer
  } = await event.request.json();

  const today = new Date();
  const formattedDate = today.toISOString().split('T')[0];
  const formattedPhone = formatPhoneNumber(driverPhone);

  const doc = new jsPDF({
    unit: 'in',
    format: [8.5, 11]
  });

  const LEFT_MARGIN = 0.8;

  doc.setFont('Helvetica', 'bold');
  doc.text('Earnings Report', LEFT_MARGIN, 1);

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(14);

  doc.text(formattedDate, 6.5, 1);

  doc.text(driverFullName, LEFT_MARGIN, 1.25);
  doc.text(formattedPhone, LEFT_MARGIN, 1.5);
  doc.text(driverEmail, LEFT_MARGIN, 1.75);

  doc.text('Reference period:', LEFT_MARGIN, 2.75);
  doc.text('Deactivation period:', LEFT_MARGIN, 3);
  doc.text('Total number of trips:', LEFT_MARGIN, 3.25);

  doc.text('Average daily pay:', LEFT_MARGIN, 4);
  doc.text('Gross estimated lost pay:', LEFT_MARGIN, 4.25);
  doc.text('Gross estimated lost pay with interest:', LEFT_MARGIN, 4.5);
  doc.text('Annual interest rate:', LEFT_MARGIN, 4.75);

  if (selectedEmployer) doc.text('Platform:', LEFT_MARGIN, 5.5);

  doc.setFont('Helvetica', 'bold');

  const CENTER_OFFSET = 4.3;
  doc.text(referencePeriodString, CENTER_OFFSET, 2.75);
  doc.text(deactivationPeriodString, CENTER_OFFSET, 3);

  doc.text(totalNumberOfTrips, CENTER_OFFSET, 3.25);

  doc.text(averageDailyPayString, CENTER_OFFSET, 4);
  doc.text(grossEstimatedLostPay, CENTER_OFFSET, 4.25);
  doc.text(grossEstimatedLostPayWithInterest, CENTER_OFFSET, 4.5);
  doc.text(annualInterestRateAsString, CENTER_OFFSET, 4.75);

  if (selectedEmployer) doc.text(selectedEmployer, CENTER_OFFSET, 5.5);

  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(11);
  doc.text('Generated by System', LEFT_MARGIN, 10.5);

  const pdfBlob = doc.output('blob');
  const responseHeaders = {
    'Content-Type': 'application/pdf'
  };
  return new Response(pdfBlob, { status: 200, headers: responseHeaders });
};

/*
Test with curl:

curl --location 'http://localhost:5173/organizer/pdf' \
--header 'Content-Type: application/json' \
--data-raw '{
    "driverFullName": "Driver Name",
    "driverPhone": "(303) 333-3333",
    "driverEmail": "email@gmail.com",
    "referencePeriodString": "2024-05-01 – 2024-06-01",
    "deactivationPeriodString": "2024-04-12 – 2024-04-28",
    "totalNumberOfTrips": "150",
    "averageDailyPayString": "$416.16",
    "grossEstimatedLostPay": "$6,658.56",
    "grossEstimatedLostPayWithInterest": "$6,725.15",
    "annualInterestRateAsString": "5%",
    "deactivationPeriodDurationString": "16 days",
    "selectedEmployer": "Uber"
}'
*/
